#!/usr/bin/env python3
"""Generate the ABI-v4 native REL catalog from DolRecomp split output."""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


CHUNK_NAME = re.compile(
    r"^chunk_\d+_rel(?P<section>\d+)_(?P<start>[0-9A-Fa-f]{8})\.c$"
)
CASE = re.compile(r"\bcase 0x[0-9A-Fa-f]{8}u:\s+goto label_")
MODULE_ID = re.compile(r"_(?P<id>\d+)$")


@dataclass(frozen=True)
class Chunk:
    start: int
    end: int


def discover(generated: Path) -> dict[int, dict[int, list[Chunk]]]:
    modules: dict[int, dict[int, list[Chunk]]] = {}
    chunk_symbols: dict[int, tuple[int, Path]] = {}
    rel_root = generated / "rels"
    if not rel_root.is_dir():
        return modules

    for module_dir in sorted(path for path in rel_root.iterdir() if path.is_dir()):
        match = MODULE_ID.search(module_dir.name)
        if not match:
            raise ValueError(f"REL output folder has no module-id suffix: {module_dir}")
        module_id = int(match.group("id"))
        if module_id == 0 or module_id in modules:
            raise ValueError(f"duplicate or invalid REL module id {module_id}")

        sections: dict[int, list[Chunk]] = defaultdict(list)
        for path in sorted((module_dir / "chunks").glob("*.c")):
            chunk_match = CHUNK_NAME.match(path.name)
            if not chunk_match:
                raise ValueError(f"unexpected REL chunk filename: {path}")
            start = int(chunk_match.group("start"), 16)
            previous_symbol = chunk_symbols.get(start)
            if previous_symbol is not None:
                previous_module, previous_path = previous_symbol
                raise ValueError(
                    f"duplicate REL chunk symbol func_{start:08X} in modules "
                    f"{previous_module} ({previous_path}) and {module_id} ({path})"
                )
            chunk_symbols[start] = (module_id, path)
            instruction_count = len(CASE.findall(path.read_text(encoding="utf-8")))
            if instruction_count == 0:
                raise ValueError(f"REL chunk contains no dispatch cases: {path}")
            end = start + instruction_count * 4
            if end > 0x1_0000_0000:
                raise ValueError(f"REL chunk address overflows 32-bit space: {path}")
            sections[int(chunk_match.group("section"))].append(Chunk(start, end))

        if not sections:
            raise ValueError(f"REL module contains no executable chunks: {module_dir}")
        for section_index, chunks in sections.items():
            chunks.sort(key=lambda chunk: chunk.start)
            for previous, current in zip(chunks, chunks[1:]):
                if previous.end != current.start:
                    raise ValueError(
                        f"REL module {module_id} section {section_index} has a "
                        f"chunk gap/overlap at 0x{current.start:08X}"
                    )
        modules[module_id] = dict(sorted(sections.items()))
    return dict(sorted(modules.items()))


def emit(modules: dict[int, dict[int, list[Chunk]]]) -> str:
    lines = [
        "/* Generated by gen_rel_module_tables.py. */",
        "",
    ]
    for module_id, sections in modules.items():
        for section_index, chunks in sections.items():
            tag = f"m{module_id}_s{section_index}"
            for chunk in chunks:
                lines.append(
                    f"void func_{chunk.start:08X}(CPUState*, u32, intptr_t);"
                )
            lines.extend(
                [
                    f"static const StaticRecompRange s_rel_{tag}_chunks[] = {{",
                    *[
                        f"    {{0x{chunk.start:08X}u, 0x{chunk.end:08X}u}},"
                        for chunk in chunks
                    ],
                    "};",
                    f"static const StaticRecompRelChunkFn s_rel_{tag}_functions[] = {{",
                    *[f"    func_{chunk.start:08X}," for chunk in chunks],
                    "};",
                    "",
                ]
            )

        lines.append(
            f"static const StaticRecompRelExecutableSection s_rel_m{module_id}_sections[] = {{"
        )
        for section_index, chunks in sections.items():
            canonical_start = chunks[0].start
            size = chunks[-1].end - canonical_start
            tag = f"m{module_id}_s{section_index}"
            lines.append(
                "    {"
                f"{section_index}u, 0u, 0x{size:08X}u, 0x{canonical_start:08X}u, "
                f"s_rel_{tag}_chunks, "
                f"(u32)(sizeof(s_rel_{tag}_chunks) / sizeof(s_rel_{tag}_chunks[0])), "
                f"NULL, NULL, s_rel_{tag}_functions"
                "},"
            )
        lines.extend(["};", ""])

    if modules:
        lines.append("static const StaticRecompRelModuleDesc s_rel_modules[] = {")
        for module_id in modules:
            lines.append(
                "    {"
                f"{module_id}u, s_rel_m{module_id}_sections, "
                f"(u32)(sizeof(s_rel_m{module_id}_sections) / "
                f"sizeof(s_rel_m{module_id}_sections[0]))"
                "},"
            )
        lines.extend(
            [
                "};",
                "#define MODULE_REL_MODULES s_rel_modules",
                "#define MODULE_REL_COUNT "
                "((u32)(sizeof(s_rel_modules) / sizeof(s_rel_modules[0])))",
            ]
        )
    else:
        lines.extend(
            [
                "#define MODULE_REL_MODULES NULL",
                "#define MODULE_REL_COUNT 0u",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "usage: gen_rel_module_tables.py <generated-dir> <output.inc>",
            file=sys.stderr,
        )
        return 2
    generated = Path(sys.argv[1])
    output = Path(sys.argv[2])
    try:
        text = emit(discover(generated))
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
