#!/usr/bin/env python3
"""Validate sparse patch PCs and emit a compile-time label-hook header."""

from __future__ import annotations

import re
import sys
from pathlib import Path


ADDRESS_RE = re.compile(r"0x[0-9A-Fa-f]{8}")
COVERAGE_RE = re.compile(
    r"address >= (0x[0-9A-Fa-f]+)u && address < (0x[0-9A-Fa-f]+)u"
)


def parse_addresses(path: Path) -> list[int]:
    addresses: list[int] = []
    for line_number, original in enumerate(path.read_text().splitlines(), 1):
        line = original.split("#", 1)[0].strip()
        if not line:
            continue
        if not ADDRESS_RE.fullmatch(line):
            raise ValueError(
                f"{path}:{line_number}: expected one 32-bit address such as 0x80123456"
            )
        address = int(line, 16)
        if address & 3:
            raise ValueError(
                f"{path}:{line_number}: patch address 0x{address:08X} is not 4-byte aligned"
            )
        addresses.append(address)

    if not addresses:
        raise ValueError(f"{path}: patch-address manifest is empty")
    if len(addresses) != len(set(addresses)):
        duplicate = next(a for i, a in enumerate(addresses) if a in addresses[:i])
        raise ValueError(f"{path}: duplicate patch address 0x{duplicate:08X}")
    if addresses != sorted(addresses):
        raise ValueError(f"{path}: patch addresses must be sorted in ascending order")
    return addresses


def parse_coverage(path: Path) -> list[tuple[int, int]]:
    coverage = [
        (int(start, 16), int(end, 16))
        for start, end in COVERAGE_RE.findall(path.read_text())
    ]
    if not coverage:
        raise ValueError(f"{path}: no DolRecomp coverage ranges found")
    return coverage


def generate(addresses_path: Path, generated_header: Path, output_path: Path) -> None:
    addresses = parse_addresses(addresses_path)
    coverage = parse_coverage(generated_header)
    for address in addresses:
        if not any(start <= address < end for start, end in coverage):
            raise ValueError(
                f"{addresses_path}: patch address 0x{address:08X} is outside "
                "the generated module's code coverage"
            )

    with output_path.open("w") as output:
        output.write("// Generated by gen_module_patch_dispatch.py -- do not edit.\n")
        output.write("#pragma once\n\n")
        output.write("struct CPUState;\n")
        output.write(
            "int moderngekko_module_patch_dispatch(struct CPUState* ctx, "
            "unsigned int address);\n\n"
        )
        output.write("#define DOLRECOMP_PATCH_PC(ctx, address) do { \\\n")
        output.write("    switch ((unsigned int)(address)) { \\\n")
        for address in addresses:
            output.write(f"    case 0x{address:08X}u: \\\n")
        output.write(
            "        if (moderngekko_module_patch_dispatch((ctx), (address))) \\\n"
        )
        output.write("            return; \\\n")
        output.write("        break; \\\n")
        output.write("    default: \\\n")
        output.write("        break; \\\n")
        output.write("    } \\\n")
        output.write("} while (0)\n")


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: gen_module_patch_dispatch.py <addresses> <generated.h> <output.h>",
            file=sys.stderr,
        )
        return 2
    try:
        generate(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
